language: python
sudo: required

before_install:
  - pip install ansible==2.6.1
  - sudo apt-get install dnsutils -y

script:
  - ansible-playbook -i tests/inventory tests/main.yml
  - dig @127.0.0.1 mysuperapp.mydomain.com
