language: python
sudo: required

before_install:
  - pip install ansible==2.6.1
  - sudo apt-get install dnsutils -y

script:
  - ansible-playbook -i tests/inventory tests/main.yml
  - ss -lnpu | grep 53
  - dig @127.0.0.1:5353 mysuperapp.mydomain.com
