language: python
sudo: required

before_install:
  - pip install ansible==2.6.1
  - sudo apt-get install dnsutils -y

script:
  - ansible-playbook -i tests/inventory tests/main.yml
  - ss -lnpu | grep 53
  - sudo cat /etc/knot/zones/mydomain.com.zone
  - sudo cat /etc/knot/knot.conf
  - dig @127.0.0.1 -p 5353 mysuperapp.mydomain.com +norecurse
