---
# Debian or Ubuntu
- name: repository keys (Debian)
  apt_key: url=http://deb.knot-dns.cz/knot/apt.key state=present
- name: repository (Debian)
  apt_repository: repo='deb http://deb.knot-dns.cz/knot/ {{ ansible_lsb['codename']}} main' state=present
- name: packages (Debian)
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
    - knot
  when: ansible_os_family == "Debian" 

# FreeBSD
- name: packages (FreeBSD)
  pkgng: name={{ item }} state=present
  with_items:
    - dns/knot2
  when: ansible_os_family == "FreeBSD"

# RedHat
# TODO: