- name: apply zone files
  copy: src={{ item.src_file }} dest={{ knot_install_dir }}/etc/knot/{{ item.name }}.zone owner={{ knot_user }} group={{ knot_group }}
  with_items: "{{ knot_zones }}"
  when: item.src_file is defined

- name: check zone files integrity
  raw: knotc zone-check {{ item.name }}
  register: "results"
  with_items: "{{ knot_zones }}"
  ignore_errors: yes

- fail: msg="A zone seems to be not loadable, please check. Trace:\n {{ item.stderr }}"
  when: item.rc != 0
  with_items: "{{ results.results }}"

- name: reload knot
  service: name={{ knot_daemon }} state=reloaded
